# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build-nix:
    docker:
    - image: nixorg/nix:circleci
    environment:
      # By default nix puts `result` in the current directory, but we don't
      # exclude that when creating the source archive.
      # Hence, the result link depends on it's previous incarnation :/
      RESULT: "/tmp/result"
    steps:
    - checkout
    - run: nix-hash --base32 ./nix ./scripts > /tmp/hashes.txt
    - restore_cache:
        name: Nix cache restore
        keys:
        - v1-hi-{{ arch }}-{{ .Branch }}-{{ checksum "/tmp/hashes.txt" }}
        - v1-hi-{{ arch }}-{{ .Branch }}
        - v1-hi-{{ arch }}-master
    - run: |
            # nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
            nix-channel --add https://nixos.org/channels/nixos-19.03-small nixpkgs
            nix-channel --update
    - run: nix-build --out-link "$RESULT"
    - run: nix-build --out-link "$RESULT" nix/services.nix
    - run: scripts/export.sh "$RESULT" /tmp/hi.nar.xz
    - save_cache:
        name: Nix cache save
        key: v1-hi-{{ arch }}-{{ .Branch }}-{{ checksum "/tmp/hashes.txt" }}
        paths:
        - /nix
    - store_artifacts:
        path: /tmp/hi.nar.xz

workflows:
  version: 2
  build_all:
    jobs:
      - build-nix