# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build-nix:
    docker:
    - image: nixorg/nix:circleci
    steps:
    - checkout
    - restore_cache:
        name: Nix cache restore
        key: v0-hi-{{ arch }}-{{ .Branch }}
    - run: |
            # nix-channel --add https://nixos.org/channels/nixos-unstable nixpkgs
            nix-channel --add https://nixos.org/channels/nixos-19.03-small nixpkgs
            nix-channel --update
            nix-env -i xz
    - run: nix-build
    - save_cache:
        name: Nix cache save
        key: v0-hi-{{ arch }}-{{ .Branch }}
        paths:
        - /nix/store
    - run: |
            nix-store -qR  result | tee closure.txt
            cat closure.txt | xargs nix-store --export | xz -v > /tmp/hi.nar.xz
    - store_artifacts:
        path: /tmp/hi.nar.xz

workflows:
  version: 2
  build_all:
    jobs:
      - build-nix